'use client';

import dynamic from 'next/dynamic';
import { TopicsPageShell } from '@/components/topics/TopicsPageShell';
import { EmptyState } from '@/components/ui/EmptyState';
import { formatDateTime } from '@/data/mock-utils';

const WuCard = dynamic(
  () => import('@npm-questionpro/wick-ui-lib').then((m) => ({ default: m.WuCard })),
  { ssr: false }
);

const SUMMARY_HISTORY = [
  {
    id: 'sum-001',
    title: 'Weekly topics summary — Mar 31, 2026',
    topicCount: 11,
    generatedAt: '2026-03-31T09:00:00Z',
    generatedBy: 'karishma.rao',
  },
  {
    id: 'sum-002',
    title: 'Weekly topics summary — Mar 24, 2026',
    topicCount: 9,
    generatedAt: '2026-03-24T09:00:00Z',
    generatedBy: 'karishma.rao',
  },
  {
    id: 'sum-003',
    title: 'Monthly topics summary — March 2026',
    topicCount: 11,
    generatedAt: '2026-03-01T08:30:00Z',
    generatedBy: 'admin.user',
  },
];

export default function SummaryHistoryPage() {
  return (
    <TopicsPageShell>
      <div className="p-6">
        {SUMMARY_HISTORY.length > 0 ? (
          <div className="flex flex-col gap-3">
            {SUMMARY_HISTORY.map((item) => (
              <WuCard key={item.id} rounded className="p-4">
                <div className="flex items-center justify-between gap-4">
                  <div>
                    <p className="text-sm font-medium text-gray-900">{item.title}</p>
                    <p className="text-xs text-gray-500 mt-1">
                      {item.topicCount} topics · Generated by {item.generatedBy} ·{' '}
                      {formatDateTime(item.generatedAt)}
                    </p>
                  </div>
                  <button
                    type="button"
                    className="text-blue-600 hover:text-blue-800 text-sm flex items-center gap-1"
                  >
                    <span className="wm-download" /> Download
                  </button>
                </div>
              </WuCard>
            ))}
          </div>
        ) : (
          <EmptyState
            icon="wm-history"
            title="No summaries yet"
            description="Use Summarize topics on the All topics page to generate your first summary."
          />
        )}
      </div>
    </TopicsPageShell>
  );
}
